project:
  type: website

website:
  title: "IS415-GAA"
  navbar:
    left: 
      - text: "Hands-on Exercise"
        menu:
          - text: "Hands-on Exercise 1"
            href: "Hands-on_Ex/Hands-on_Ex01/hands-on_ex01.html"
          - text: "Hands-on Exercise 2"
            href: "Hands-on_Ex/Hands-on_Ex02/hands-on_ex02.html"
          - text: "Hands-on Exercise 3"
            href: "Hands-on_Ex/Hands-on_Ex03/hands-on_ex03.html"
          - text: "Hands-in Exercise 3.1"
            href: "Hands-on_Ex/Hands-on_Ex03.1/hands-on_ex03.1.html"
          - text: "Hands-in Exercise 4"
            href: "Hands-on_Ex/Hands-on_Ex06/hands-on_ex6.html"
          - text: "Hands-in Exercise 5"
            href: "Hands-on_Ex/Hands-on_Ex09/hands-on_ex9.html"
          - text: "Hands-in Exercise 6"
            href: "Hands-on_Ex/Hands-on_Ex10/hands-on_ex10.html"
          - text: "Hands-in Exercise 7"
            href: "Hands-on_Ex/Hands-on_Ex13/hands-on_ex13.html"
          - text: "Hands-in Exercise 8"
            href: "Hands-on_Ex/Hands-on_Ex16/hands-on_ex16.html"
            
      - text: "In-Class Exercise"
        menu:
          - text: "In-Class Exercise 2"
            href: "In-Class_Ex/In-Class_Ex02/in-class_ex02.html"
          - text: "In-Class Exercise 3"
            href: "In-Class_Ex/In-Class_Ex03/in-class_ex03.html"
          - text: "In-Class Exercise 4"
            href: "In-Class_Ex/In-Class_Ex04/in-class_ex04.html"
          - text: "In-Class Exercise 5"
            href: "In-Class_Ex/In-Class_Ex05/in-class_ex05.html"
          - text: "In-Class Exercise 6"
            href: "In-Class_Ex/In-Class_Ex06/in-class_ex06.html"
          - text: "In-Class Exercise 7 (GLSA)"
            href: "In-Class_Ex/In-Class_Ex07/in-class_ex07.html"
          - text: "In-Class Exercise 7 (EHSA)"
            href: "In-Class_Ex/In-Class_Ex07/in-class_ex07-1.html"
          - text: "In-Class Exercise 8"
            href: "In-Class_Ex/In-Class_Ex08/in-class_ex08.html"
          - text: "In-Class Exercise 9: gwML"
            href: "In-Class_Ex/In-Class_Ex09/in-class_ex09.html"
          - text: "In-Class Exercise 10: SIM"
            href: "In-Class_Ex/In-Class_Ex10/in-class_ex10.html"
          - text: "In-Class Exercise 11: Accessibility Models"
            href: "In-Class_Ex/In-Class_Ex11/in-class_ex11.html"
          - text: "In-Class Exercise 12: Accessibility Models"
            href: "In-Class_Ex/In-Class_Ex12/in-class_ex12.html"
      - text: "Take-home Exercise"
        menu:
          - text: "Take-home Exercise 1"
            href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"
          - text: "Take-home Exercise 2"
            href: "Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html"
          - text: "Take-home Exercise 3"
            href: "Take-home_Ex/Take-home_Ex03/Take-home_Ex03.html"
       
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true

editor: visual

